baseURL: https://www.changelog.com.cn/
languageCode: zh-CN
title: Changelog
theme: PaperMod

params:
  env: production
  profileMode:
    enabled: true
    title: Changelog
    subtitle: "Programming, Database, Software"
    buttons:
      - name: Posts
        url: posts
  assets:
    favicon: "/favicon.png"
    favicon16x16: "/favicon.png"
    favicon32x32: "/favicon.png"

markup:
  highlight:
    tabWidth: 2

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 20
