baseURL: http://www.changelog.com.cn/
languageCode: en-us
title: Changelog
theme: PaperMod

params:
  env: production
  profileMode:
    enabled: true
    title: Changelog
    subtitle: "Software, Database, InfoSec"
    buttons:
      - name: Posts
        url: posts

markup:
  highlight:
    tabWidth: 2

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 20